# 基础配置
runmode: debug
addr: :8080
uri: http://127.0.0.1:8080
max_retry_count: 3

# 日志配置
log:
  writers: file,stdout
  logger_level: DEBUG
  logger_file: logs/log.log
  log_format_text: false
  rollingPolicy: daily # size, daily
  log_rotate_date: 1
  log_rotate_size: 1
  log_backup_count: 7

# 数据库配置
db:
  name: db_apiserver
  addr: 127.0.0.1:3306
  user: root
  passwd: 123456
docker_db:
  name: db_apiserver
  addr: 127.0.0.1:3306
  user: root
  passwd: 123456
